baseURL = "http://lucytutors.co.uk"
languageCode = "en-us"
title = "Lucy Tutors"
theme = "hugo-alageek-theme"
publishDir = "docs"
author = "Lucy Whalley"

[params]
logofile = "https://lucydot.github.io/img/title.png"


