baseURL = "https://lucydot.github.io/LucyTutors/"
languageCode = "en-us"
title = "Lucy Tutors"
theme = "hugo-alageek-theme"
publishDir = "docs"
author = "Lucy Whalley"

[params]
logofile = "http://lucydot.github.io/LucyTutors/img/title.png"


